apiVersion: v1
kind: Service
metadata:
  name: casper-service
  labels:
    run: casper
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    run: casper
