apiVersion: apps/v1
kind: Deployment
metadata:
  name: casper
spec:
  selector:
    matchLabels:
      run: casper
  replicas: 1
  template:
    metadata:
      labels:
        run: casper
    spec:
      containers:
      - name: casper
        image: jonnybinthemix/casper:1.0.0
        imagePullPolicy: Always
        env:
          - name: SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: slack-token
                key: SLACK_TOKEN
          - name: SIGN_SECRET
            valueFrom:
              secretKeyRef:
                name: sign-secret
                key: SIGN_SECRET
          - name: PYOWM_KEY
            valueFrom:
              secretKeyRef:
                name: pyowm-key
                key: PYOWM_KEY
          - name: CRYPTO_KEY
            valueFrom:
              secretKeyRef:
                name: crypto-key
                key: CRYPTO_KEY
        ports:
        - containerPort: 5000
