apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
spec:
  selector:
    matchLabels:
      app: ngrok
  replicas: 1
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
      - name: ngrok
        image: jonnybinthemix/ngrok:1.0.0
        imagePullPolicy: Always
        env:
        - name: NGROK_AUTH
          valueFrom:
            secretKeyRef:
              name: ngrok-auth
              key: ngrok-auth
        command: ["/bin/sh"]
        args:
          - -c
          - >-
            ngrok authtoken $NGROK_AUTH &&
            ngrok http casper-service:5000
        ports:
        - containerPort: 4040
