
name: Casper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }} 
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build Casper Docker Image
      run: |
        docker build -t jonnybinthemix/casper:1.0.0 .
    - name: Build NGROK Docker Image
      run: |
        docker build -t jonnybinthemix/ngrok:1.0.0 ./ngrok
    - name: Docker Push
      run: |
        docker push jonnybinthemix/casper:1.0.0
        docker push jonnybinthemix/ngrok:1.0.0

             
